### ISSUE TITLE
httpOnly cookie set in the front-end not being sent to the server

### ISSUE THREAD

**Issue by notsag-dev** [ItsBenCodes/cookies#180]
Hi all, I'm trying to set a cookie in the front-end with httpOnly=true to store the authentication token. The problem is that it's not being sent to the server in a request that should include it, while other cookie set with httpOnly=false is included. Here is how I'm setting both cookies:

```
let cookies = new Cookies();
cookies.set('token', token, {httpOnly: true, secure: false, path: '/'});
cookies.set('user', JSON.stringify(user), {httpOnly: false, path: '/'});
```

The request is performed using axios setting withCredentials=true:
```
const {data: opinions} = await axios(
   {
        method: 'get',
        baseURL: process.env.REACT_APP_API_URL,
        url: process.env.REACT_APP_API_OPINIONS,
        withCredentials: true,
   });
```

As I said before, the cookie 'user' is being sent. The request is a CORS request with the same IP but different port. I also tried setting the domain property in the cookies.set call with no success. Any idea?

Thanks.

**Comment by Verten** [comment]
yes, i have the same issue.

**Comment by Verten** [comment]
@notsag-dev have you fix this problem?

**Comment by notsag-dev** [comment]
Unfortunately we haven't, for now we aren't using the httpOnly option which is not a good idea. An option could be setting the cookie on the server side, but I don't think you can do that for a CORS request anyways, even if you have control over the API. Will let you know if we find a solution for this.

**Comment by abatilo** [comment]
@eXon What's the point of `httpOnly` being a part of `CookieSetOptions` if you can't set it from the client side to begin with?
